/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { VaultItemService } from "../vaultItem.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VaultItemCreateInput } from "./VaultItemCreateInput";
import { VaultItem } from "./VaultItem";
import { VaultItemFindManyArgs } from "./VaultItemFindManyArgs";
import { VaultItemWhereUniqueInput } from "./VaultItemWhereUniqueInput";
import { VaultItemUpdateInput } from "./VaultItemUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class VaultItemControllerBase {
  constructor(
    protected readonly service: VaultItemService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: VaultItem })
  @nestAccessControl.UseRoles({
    resource: "VaultItem",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createVaultItem(
    @common.Body() data: VaultItemCreateInput
  ): Promise<VaultItem> {
    return await this.service.createVaultItem({
      data: {
        ...data,

        vault: data.vault
          ? {
              connect: data.vault,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        typeField: true,
        updatedAt: true,

        vault: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [VaultItem] })
  @ApiNestedQuery(VaultItemFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "VaultItem",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async vaultItems(@common.Req() request: Request): Promise<VaultItem[]> {
    const args = plainToClass(VaultItemFindManyArgs, request.query);
    return this.service.vaultItems({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        typeField: true,
        updatedAt: true,

        vault: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: VaultItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VaultItem",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async vaultItem(
    @common.Param() params: VaultItemWhereUniqueInput
  ): Promise<VaultItem | null> {
    const result = await this.service.vaultItem({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        typeField: true,
        updatedAt: true,

        vault: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: VaultItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VaultItem",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateVaultItem(
    @common.Param() params: VaultItemWhereUniqueInput,
    @common.Body() data: VaultItemUpdateInput
  ): Promise<VaultItem | null> {
    try {
      return await this.service.updateVaultItem({
        where: params,
        data: {
          ...data,

          vault: data.vault
            ? {
                connect: data.vault,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          typeField: true,
          updatedAt: true,

          vault: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: VaultItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VaultItem",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteVaultItem(
    @common.Param() params: VaultItemWhereUniqueInput
  ): Promise<VaultItem | null> {
    try {
      return await this.service.deleteVaultItem({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          typeField: true,
          updatedAt: true,

          vault: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
